
services:
  jupyter:
    container_name: jupyter
    image: jupyter-environment
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    user: root
    environment:
      - NB_UID=${UID}
      - NB_GID=${GID}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - JUPYTER_ENABLE_LAB=${JUPYTER_ENABLE_LAB}
      - GRANT_SUDO=${GRANT_SUDO}
    volumes:
      - ./data/interim:/data/interim
      - ./data/logs:/data/logs
      - ./data/models:/data/models
      - ./data/processed:/data/processed
      - ./data/raw:/data/raw
      - ./notebooks:/home/jovyan/work/notebooks
      - ./reports:/reports
      - ./src:/home/jovyan/work/src
      - ./config/settings.yaml:/config/settings.yaml
    ports:
      - "8888:8888"
    networks:
      - ds-network

networks:
  ds-network:
