services:
  jupyter:
    container_name: question-answering-jupyter
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    user: root
    env_file:
      - .env
    volumes:
      - ./data/interim:/data/interim
      - ./data/processed:/data/processed
      - ./data/raw:/data/raw
      - ./notebooks:/home/jovyan/work/notebooks
      - ./src:/home/jovyan/work/src
      - ./config/settings.yaml:/config/settings.yaml
    ports:
      - "8888:8888"
    networks:
      - ds-network

networks:
  ds-network:
