logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO

volumes:
  external: /data/external/
  interim: /data/interim/
  logs: /data/logs/
  models: /data/models/
  processed: /data/processed/
  raw: /data/raw/
  reports: /reports/

MODEL_NAME: "google"
GOOGLE_MODEL_ID: "gemini-2.5-flash-preview-04-17"
OPENAI_MODEL_ID: "gpt-4o-2024-08-06"
