logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO

volumes:
  external: /data/external/
  interim: /data/interim/
  logs: /data/logs/
  models: /data/models/
  processed: /data/processed/
  raw: /data/raw/
  reports: /reports/

MODEL_NAME: "google"
TEMPERATURE: 0
GOOGLE_MODEL_ID: "gemini-2.0-flash"
OPENAI_MODEL_ID: "gpt-4.1-nano-2025-04-14"
