logging:
  formatter:
    format: '%(asctime)s - %(message)s'
    time_format: '%Y-%m-%d %H:%M:%S'
  level: INFO

volumes:
  external: /data/external/
  interim: /data/interim/
  logs: /data/logs/
  models: /data/models/
  processed: /data/processed/
  raw: /data/raw/
  reports: /reports/

MODEL_NAME: "google"
TEMPERATURE: 1
GOOGLE_MODEL_ID: "gemini-2.5-flash-preview-04-17"
OPENAI_MODEL_ID: "o4-mini-2025-04-16"

# "gpt-4.1-mini-2025-04-14"

# "o4-mini-2025-04-16"
